#!/bin/sh

# not interactive so do nothing
[[ $- != *i* ]] && return

# HISTORY
# append to history
shopt -s histappend
# no duplicates
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=1000
HISTFILESIZE=2000

# update LINES and COLUMNS after window resizing
shopt -s checkwinsize

# make less more friendly for non-text input
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

for filename in $HOME/.sources/*; do
  source $filename
done

# PROMPT
color_num=2 # green
symbol=$
# if root, change color and symbol
if [[ ${EUID} == 0 ]] ; then
  color_num=1 # red
  symbol="#"
fi
export PS1="\[\033[01;3${color_num}m\]\w\[\033[01;34m\]\$(__git_ps1 ' (%s)')\n${symbol} \[\033[00m\]"

unset color_num
unset symbol

export EDITOR='emacs -nw'
export VISUAL='emacs -nw'
export BROWSER='google-chrome'

export PATH=$HOME/.bin:$PATH

export ANDROID_HOME=/Users/$USER/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/bin
#export PATH="/usr/local/opt/ruby/bin:$PATH"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"
#export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
